# Configuration: Manage settings (openSUSE Leap, os-update).

---

- name: "Config | SUSE | Notice: options not supported by os-update are ignored"
  ansible.builtin.debug:
    msg: >-
      The os-update backuend does not support the following requested option(s):
      {{
        ((['auto_update_linux_apply=' ~ auto_update_linux_apply ~ ' (only install is supported)']
          if auto_update_linux_apply != 'install' else [])
        + (['auto_update_linux_exclude (' ~ (auto_update_linux_exclude | ansible.builtin.length) ~ ' entries)']
          if (auto_update_linux_exclude | ansible.builtin.length) > 0 else [])
        + (['auto_update_linux_notify_email']
          if (auto_update_linux_notify_email | ansible.builtin.length) > 0 else []))
        | ansible.builtin.join(', ')
      }}
  when:
    - (auto_update_linux_apply != 'install') or
      ((auto_update_linux_exclude | ansible.builtin.length) > 0) or
      ((auto_update_linux_notify_email | ansible.builtin.length) > 0)


- name: "Config | SUSE | Create os-update configuration"
  ansible.builtin.template:
    src: "os_update.conf.j2"
    dest: "{{ __auto_update_linux_osupdate_config_file_path }}"
    owner: "{{ __auto_update_linux_osupdate_config_file_owner }}"
    group: "{{ __auto_update_linux_osupdate_config_file_group }}"
    mode: "{{ __auto_update_linux_osupdate_config_file_mode }}"
