# Role argument validation.
#
# For information on the argument_specs.yml, see the official documentation:
# https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_reuse_roles.html#role-argument-validation

---

argument_specs:

  # foundata.linux/roles/run/tasks/main.yml entry point
  main:
    short_description: "Main entry point for the foundata.linux.sudo role"
    options:

      sudo_linux_state:
        type: "str"
        required: true
        choices:
          - "present"
          - "absent"

      sudo_linux_autoupgrade:
        type: "bool"
        required: true

      sudo_linux_service_state:
        type: "str"
        required: true
        choices:
          - "enabled"
          - "disabled"
          - "running"
          - "unmanaged"
